/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedLayoutRouteImport } from './routes/_authed/layout'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as ExploreAnimalIdRouteImport } from './routes/explore/$animalId'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedProfileEditRouteImport } from './routes/_authed/profile/edit'
import { Route as AuthedQuizAnimalIdRouteImport } from './routes/_authed/quiz/$animalId'
import { Route as AuthedQuizResultQuizIdRouteImport } from './routes/_authed/quiz/result/$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutRoute = AuthedLayoutRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreAnimalIdRoute = ExploreAnimalIdRouteImport.update({
  id: '/explore/$animalId',
  path: '/explore/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedLayoutRoute,
} as any)
const AuthedProfileEditRoute = AuthedProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => AuthedLayoutRoute,
} as any)
const AuthedQuizAnimalIdRoute = AuthedQuizAnimalIdRouteImport.update({
  id: '/quiz/$animalId',
  path: '/quiz/$animalId',
  getParentRoute: () => AuthedLayoutRoute,
} as any)
const AuthedQuizResultQuizIdRoute = AuthedQuizResultQuizIdRouteImport.update({
  id: '/quiz/result/$quizId',
  path: '/quiz/result/$quizId',
  getParentRoute: () => AuthedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/explore/$animalId': typeof ExploreAnimalIdRoute
  '/explore/': typeof ExploreIndexRoute
  '/profile/edit': typeof AuthedProfileEditRoute
  '/quiz/$animalId': typeof AuthedQuizAnimalIdRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/quiz/result/$quizId': typeof AuthedQuizResultQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/explore/$animalId': typeof ExploreAnimalIdRoute
  '/explore': typeof ExploreIndexRoute
  '/profile/edit': typeof AuthedProfileEditRoute
  '/quiz/$animalId': typeof AuthedQuizAnimalIdRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/quiz/result/$quizId': typeof AuthedQuizResultQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/explore/$animalId': typeof ExploreAnimalIdRoute
  '/explore/': typeof ExploreIndexRoute
  '/_authed/profile/edit': typeof AuthedProfileEditRoute
  '/_authed/quiz/$animalId': typeof AuthedQuizAnimalIdRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/quiz/result/$quizId': typeof AuthedQuizResultQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/explore/$animalId'
    | '/explore/'
    | '/profile/edit'
    | '/quiz/$animalId'
    | '/profile/'
    | '/quiz/result/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/explore/$animalId'
    | '/explore'
    | '/profile/edit'
    | '/quiz/$animalId'
    | '/profile'
    | '/quiz/result/$quizId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/login'
    | '/signup'
    | '/explore/$animalId'
    | '/explore/'
    | '/_authed/profile/edit'
    | '/_authed/quiz/$animalId'
    | '/_authed/profile/'
    | '/_authed/quiz/result/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedLayoutRoute: typeof AuthedLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ExploreAnimalIdRoute: typeof ExploreAnimalIdRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$animalId': {
      id: '/explore/$animalId'
      path: '/explore/$animalId'
      fullPath: '/explore/$animalId'
      preLoaderRoute: typeof ExploreAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
    '/_authed/profile/edit': {
      id: '/_authed/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthedProfileEditRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
    '/_authed/quiz/$animalId': {
      id: '/_authed/quiz/$animalId'
      path: '/quiz/$animalId'
      fullPath: '/quiz/$animalId'
      preLoaderRoute: typeof AuthedQuizAnimalIdRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
    '/_authed/quiz/result/$quizId': {
      id: '/_authed/quiz/result/$quizId'
      path: '/quiz/result/$quizId'
      fullPath: '/quiz/result/$quizId'
      preLoaderRoute: typeof AuthedQuizResultQuizIdRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
  }
}

interface AuthedLayoutRouteChildren {
  AuthedProfileEditRoute: typeof AuthedProfileEditRoute
  AuthedQuizAnimalIdRoute: typeof AuthedQuizAnimalIdRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
  AuthedQuizResultQuizIdRoute: typeof AuthedQuizResultQuizIdRoute
}

const AuthedLayoutRouteChildren: AuthedLayoutRouteChildren = {
  AuthedProfileEditRoute: AuthedProfileEditRoute,
  AuthedQuizAnimalIdRoute: AuthedQuizAnimalIdRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
  AuthedQuizResultQuizIdRoute: AuthedQuizResultQuizIdRoute,
}

const AuthedLayoutRouteWithChildren = AuthedLayoutRoute._addFileChildren(
  AuthedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedLayoutRoute: AuthedLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ExploreAnimalIdRoute: ExploreAnimalIdRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
